DOCKER_COMPOSE_VERSION: 1.22.0

env:
  # staging deployment passphrase (for key 627acbd0c2b25992)
  - secure: n8F1mV21D3vwfkjI1+s1AYhJJ7gAAgp0NwUbgp1An5ezG/1fNf0mcrN4n/mXVKKjkYKUasNwFkRzr7c4zYQRH6LBt+lIaLjw1k9BMBADbalRnXK3ipO+0s+i0Xd9qPLGkiOVM9Hl24lcj
QNDeCXyH9FfPYHokcCBk88SbE5z7IYnChajybh0T7owv7oJPbOMVwjGaNranjlzGys4aG7ADpCcfRlyLKX/p8wjxXMXYB5Hue6H3vqGpSm+b/klhuOHh9WmowLGC2hYp+mmGaAGGgDdm/R
m4A5EbpTm8VJMoi2REwgkrZWFsG3EE/IJmCOUKUA8GyeRB7yd3gbe9Lnp24GfXmNH/PEcQRFZaVbps4EkYaWCDmDULb2vvxUgc7zdGoOVtqjpKb1Hg79Jjr7z0VnALGjGI8JWFhLihQT/g
LyFufHbh/y1uXbiRuFdsULU5KPNm5b4co1BDblJ88KZCCbnDC/exMN01ycgOhCjn0qfjQSfp6yDMfa+I1nnKOTtHNhqXnbrqnxi4YddIzaSXBgTBtthfiLaocDBv9qG/DKeroDhe9KjWD6
I3WcUpqLOep0bbrB9IB87CDBecMFUQHFwcEotfyl6iBIRY9YDfLs2CzeBCN76YaSd0JmBDcNL7wAMDDBUFW4nbY8kCktlDyNOCbDWiWMNae6fmTx0wqw=

script:
 - docker-compose pull
 - docker-compose build

after_success:
  - if [ \
      "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" != false ] \
    ]; then
      for ENC_KEY in $(cd keys && ls *.enc); do
        PASSPHRASE_VAR_NAME="TRAVIS_PASSWORD_${ENC_KEY%.enc}"
        ssh-keygen -p -P ${!PASSPHRASE_VAR_NAME} -N "" keys/$ENC_KEY &&
          mv keys/$ENC_KEY keys/${ENC_KEY%.enc}.key
      done
    fi
  - export ENV=.env.staging; (. $ENV && ./scripts/deploy.sh)
