DOCKER_COMPOSE_VERSION: 1.22.0

env:
  global:
    # TRAVIS_PASSWORD_a4a4667750982126 (to deploy .env.staging)
    - secure: "CO0Ynr1CxJCjk91/jY+NP+kTrtCeC744ePj8c6hY0zDhqmQTdKfiK7bLXPYgAZo8GFo+yHWnLrhO3YFt77Ovr1CrynRxY0FoFY+7yZi2wAD8cBptA3GwypjYP39Fhtre8QkpltAPoR2wJ5bUTvgO+STQRQ8Ab8ilZlFtTUDjNEZdsOUgRucnkKk99joeMho1Gsji2/2tqrpndAj0RSTv1P5TOkgpZd9tC9gxtRUCBrXCTDP09/shunzahOf9UPTklc6AEE9vFB9g3mi59gcWAnCsuoP0DoOf5nQzEvDYDoWbFrYGGaSIBYM7j4F/foLmcwHEYxajGwuUqe12H42iBZWQiTd/BdbTFExzC/ycAhqoiemdpF/lYtZ8rqVUw4wtgwJmZc5EPbkHoVl2pcdY0bkHr1xe4TXxCZnI7NANeJinBpcCkGWLUMXXALL3R6oZ+zeHNrQ0pXRQpxbafdJEWYnnqqGf2Sa+9HUhtA9nsl4a/Fu2mvNlaZ0vHn3Z5LBk6PAsUktNwZqHUIcyOcBa5hQ0n8Oo1nqdiDwb3A3k7OjjiQM9UO+vLz44nzrkKn5/X9x0qcYWP8lPQxa4socTN0cOMaj4cdIsXB4DoFE7MSml1TEc6139zungicbhF2y+0gFx+fTLJeLnFGHenKKoxIYf75GzyOCBgoQaM1qV28o="
    # TRAVIS_PASSWORD_64af3355ad597d51 (to deploy .env)
    - secure: "VsTCxrxH7BaXlkkg5THCedXzEb5yNh1X+vdcrQxveGzW/xCMyHPJ7lMje3014m9YpjJSGdZayFflpP7NSgGziL1TR1DB53YeAykrnsQNqbSUU0x92DA3KJ7CdPWyxlIhZujYa9zfEPQx8omuiEVaG1+KHLBbDolNG2KayPyM7K20tNormiWL8RExIMg+VgMapRU7oHAvU5H99H+XIXEDdVhBNCA2hO/U1lhBMkNXJoqFU2Td3zJ/Y+fmSUBaUPoBvzflzq4KR7GCTVT1mxrxm+//NBeZLAPMGc9+RM0mB9NAURiyxovR6koBoql4yv22482ioTUstYdvszR82rY/RvGnItq4KbZvd5te8M3EabzwQlb/zUMK8jRAnOlHtX6LErFxeyHLXiT7dxh9qOkcB61hX6udC3ZWVq7KoYMeWgxUdGfxUV0F5JeWRuhNwqRvxDSjA/xIqytemjJeRIBCyvalIMDhhkEDfobJd76bltQgPl4hFHSbNf6ZMHGieu3gaEJV/0NZu3u8EcS6yvpx5ducT3U7KvIOdV8ntthOF2bzNScBRUbXqfWgw6ibHLj0cOHBwpdfrFBezI8Lb68tkduGuu2UOpQeKCw2xA5rfSVc23R0Qvc9rljnB/0ndgb8GSf67utrveQ156mNdPORoRNqPBnGnYA6xYRWu+7DQ6Q="

before_install:
  - sudo apt-get install jq

script:
 - docker-compose pull
 - docker-compose build

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ];
    then
      export ENV=.env.staging;
      (. $ENV && ./scripts/deploy.sh);
    fi
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ];
    then
      export ENV=.env;
      (. $ENV && ./scripts/deploy.sh);
    fi
