DOCKER_COMPOSE_VERSION: 1.22.0

env:
  global:
    # TRAVIS_PASSWORD_21eed794827f82d1 (to deploy .env.staging)
    - secure: "aHrpNMBnYAs3ksSUbPUXhBv7Q2BVcUUela2WNB3BKX06mfkgnSaNeKxN6tasyPt2ZU/b3MX/ghpjgpyUBfppE8hJdYwP0mK2p6tTetrlfn5+mP18t4ZG1Ist8Am9gM4IRX6X15Dg3j/fDm6IT5ftcd5G26mo70uUfvYi+4mlhsWOOCgg6e9F/GHeDeWo4jrYu/JCyDd7zz1s424zUy+8jeZcA7xVaIIwNXQClnrT/Inj8G/LBemiZc8R0gITimiEfuAZNY3Y/ZvlQE0+eSPSMdnIkceSYk9SRiypa7Bxr1IvUVIaGjH51QtBZEg9yVdXtIMfLX2DyuROKDKSdPnI7I8ypcSn64zyshlNti3NxIJvkzCXhIeVK+c+yfWjzGyKA5B1DYTLWH8BaSbUloWvvIMvQC8mtk9360nTCoNHVX000FJj7EEbBFPghvuNVPBSl5ifk/5imWlQYeba4fDl86A6t2/BQe1dll+gnRC1VJ9gHN26SJh5l9vjFPhpsgPDLlGg9l4iZCO38Svhy8SnEUq1hVy00YfqphczqGsQ+CyOzrIVA479zCYOcFQqPVovn0t+GALsXNrx+jnhjTmdMHVVy+mePQ+/D3J7HZNa/6Fxr9y7W2ro2GEf9Pqb/U699wjkTrQTeo7OTNfTZSOnt3pxwZSs8kIAoKMX1aagZ3g="
    # TRAVIS_PASSWORD_f4e0d6c1d51723d3 (to deploy .env.staging-2)
    - secure: "ougtbU7dGr+47D5U4+3dYLixAP29nuIFxffj7vLgiKZmmufnp+TQ5DkZyHY0M5Q2p8gtrz64t21TLhNMgpdyxAVpUwVdq4rqN8YCQhpmb32/1dEirYZT1aSHpQ09Rf6pu/sA4zadSO8zmE2i1ygPJ7sglZZjQXg6RN3YcQtvhKUMTuOrpl4XYDW00uoDA4zT6//BBedmhIXkqH4d1et8UUAPfrizRpHS7mdLL5+cKsZfHZMxUAweooOXg5M7QiCmzF0Um6PdZ4Zb9jzDAENgknnPy2CKAGS3zMGvgIegNX+7kGict9dDVchc4PXE2i0vAuj+mK5LuZv4A++ynyil8c5PletWypRqfBTxemtMzO+Itd4AsVpKzk5QwYGFaHuxZNOo60LbEIfOOSc+vIFVc2J5uJG88CLCVAnaMMUlOb7OZrArTB3oGQYHIwFodMSO7BxuJG71bKIqg06OpU2Lo8vERQFBp5TYY0YADU3ozz5uoPD4bVjJDKmkoMMQhl+0YIB9NdMk2FNBQGabr0YxAY9bwlQVfGCVXyBOSLD6WF+xdce4BltJNI+t8e4dszVNzrCXLr6PCOP2T/TmDrtrlRVSXKXZg1at3UxYVWr0KXNt8pOfU6iKCn72NzPcGCOXkdWZrRYgO+xHL5UrufDcEl+dfPtGzjhUF8Zytxtp710="
    # TRAVIS_PASSWORD_6998d03f8b7f08a4 (to deploy .env)
    - secure: "bNF+HjCB1Xz8vF4K1v8RTA26KD3rDvGg7NaCR1z0O+w1PRyjOgedQbWyAM1+t+IRZ9rVqIsQ6CavSae88x5rPKHE1IKjrgBrOi1mpYYm+9XumLPRaVxwE9RaaQGtjkPwk3mo/UW+4RppkXpUyr0kcSSf5W21keTe8ryEb5gghL6pfvHaL6WB1/tfBap/Ih0PvWF3kbI/zi8xYNiGBm3EkzPpCYawvjnJwlLBBx0ZZPSd3LJSe3lT0vx3uML78e1svCUDdClue6iF25kMfufNxpWaomKfevMNBW2MBN9poBt9eNXVRp3FadAEep4emgEs/BGRa849Fh4ZG3vO7K8op3EZ4/s3ej57iFsw5q8FdVaE0o60Go2hwHqxybaU5zTgmSaDkEn8kbptzATszCWcLXms+57uY7n6KPKvaG9tAc0hbHRm7brWlLSB5qkCkvSdoQbzriZwT3GbhhLa7VpexQp/uQf+bHu/2vU10SPFHcX/6VLUVb4XFbNC/CiwV72kdFp6BtHCSMCeiQ9sKyEHd0iROy1MzTKUT++KcY3PShSkXl2IeF0Y3i2FqhJw+A67g2o2ga4uYn8L7c1XJlSnFkziPHL4lWsYC79zkWA2HZIF09h60RF7PPoAagglNQNQCDyfE57s9zd+Qt/pl+a5NoQb71bTQYPDgCuOsZf3O6M="

before_install:
  - sudo apt-get install jq dnsutils

script:
  - docker-compose pull
  - docker-compose build
  - docker run -e JUST_PRINT_AUDIT_PAGE=1 dappsearth_frontend > audit.html.expected
  - diff audit.html audit.html.expected
  - rm -f audit.html.expected

after_success:
  - ./scripts/travis-deploy.sh .env.staging
  - ./scripts/travis-deploy.sh .env.staging-2
  - ./scripts/travis-deploy.sh .env
