DOCKER_COMPOSE_VERSION: 1.22.0

env:
  global:
    # TRAVIS_PASSWORD_6a75f6660390ce2f (to deploy .env.staging)
    - secure: "HzVnVUrKd1893kbXUdHNporP3NPr/nHVsXs9e4LbE3E+N3sWaFuFIVc1DFkGYU6BSkz7oQFtuXGLUKy0Gb4WuamNeLqWTmsiRLuGblq6SoSgVBzUTDdjhKQdN4vQBfudA12HZ32qwFBm7MIwZzngO8lALYQJEba4Y0K2YoJHMtkutFlPG9VJfHoeNAZOt/jM1kGlBYapchBr3XzNx4uNYeDItvHNDsnewUTPpvVWtdsJiA+YSDkToNqapgXclYz5kQNMrB8jT8DUkco7MaGqrngIPQ5fXR6LqHqnPq5aN+Cj6rgRuDmP5uz8ADCrTR5+6U+Lh7vXShnHxs6u7/BggLKjnsPa6CHnn0G5GlrLUlU60uzwFGvH1tIWW0cj67fdxR3/j7EcYDe7V4SBWAAd6q13tMEi6sr8lO8LuUsfEjp3mwgaep6HqhB3Vacdv+bNirED566JrlKsPLsnY8nIrRHYagBLydlhsdtOr8vkOEvEPGw0Y8MpJry0wBH6cqPaLvKaVC+gxFyRH214rpAPE4lfcBAFEPhwi8fwRbuvfidjgzce0b+zIJlmWQMmE5B6yal61fmCHJc/JyHLL6VnpBzwyVz7WzF/KPtTkbYjGshHOSe32H++GmMg99DIu+m5R7Wjj3C9DW15j9rywyaqG31XEVrwsO013EoxxO6qLZ8="
    # TRAVIS_PASSWORD_0fdd06da3f1beacf (to deploy .env)
    - secure: "S/Adtt/3AIU9B8dQWsRxxN4+VB7yQn0Io9JUm/57AeKuzjePThsqByuK/UxGB27JNycnShoSszoLsofev+QSAeGGdTdDJ+6aZL1Ozr/MvPJbfM8+uyZc8KMWhPzQ+inuhfQ8UjUb6EpyClhPLKDuINMhrawNrSB7Bextq8EAJddclSsMUj73DBJStDI84YWemfTwRvy/cZWZqDH7x2l0J0kxhBLIaJEJ4C0r3u/t3wmrZ33CqZhIiFaoI8KEK4NtGwnJMkGyuW224hsFC9V3yMXL+PUyV8NVDF7KtQGPr3GdBjkpn8Stsx3hFdtXzT8N4UwGMAzDYA97QActIKunKZFqNEhvX8hszzpznGOhNwUuhjwQu1BbmnuQBl9BS6/k+E3KyDS85xQ8NfmkLclIZ71qSu2JFr9qqsjeAw0UZQ3aAeqsDo7nd2LcPZudNo6wBclyd2pHREGz493x4BCblRsVoKbrV8mMfmDWSC7r3+9o9MkeMPQHtAeEX3/JxanMHuPJe7HyKWZhMzoqWyZQUfgAoRhHDepcLWJ73JFV07FuW2HPtWnQ9qhqdaZDMa2QszbCt/cqIgKB+2chec7d5Fv1BYJFlMb9PbGwdwsbZJ1ZwFxG6KYDsXTb3dJsG4XYI+feel50VRjH2ULwo7Pyzw9tYrJ5MdnZ6KD427iQULI="
    # TRAVIS_PASSWORD_18a2443f8d4f56ee (to deploy .env next)
    - secure: "BLuR66KU7XTh4YBkP7mmQV/fgppNnlzNSZM4RNUC1I0mLiZdQmD6+cXboKjl1xquJurmfehJBVg/WNxMyzBnnaThzqF9rHAXXikJQWAw66dAnAPISwz+kRN2KNwZvUGvkK2ANFaeVWJ/hC6g1T+AZBfFEEfcZbNdEQZkgRcr7lTDBvv5SAyWLnlF3qdGqFbiMUIaZOPvbFbh2WPpFCYRyMGlcw6FJShtJhY5dlDHzYhBL0qRAs8filwc8DntW52Vg9R0he0LzbBICFGuA6Dn//zT2m63+HMxk+Y2T2jT2NVbcwlSOcTKTwJpebTuFLU6v7xyIuREcZOvTK3O9SZcfU4jnAWin9OeS9bBU1yvCiQBQ20UyttuSstMWOgXY66mW+e8IvUjzjgea7JRkV/B0W9dtuAQ+9IDzNqY6juXdUuvF8IGPMddZz0VtACmwpGRm7ZbhsdTr4qOn7/Sjf2MbKRmJUbCQzLiFREPzdm+r9xX7tUUKlRFdqjakJxDvQgl5EbCm53b8LNFNDDWescuHpRGDby9tQXe/3495oFJIukix3+G6VQ8/K0HhUPBOYd/WVw3hICzCTmMsYf9rkYHdx+WKc1RWbxD8i1h1E7tr3HHApFlFfw9pxFoHtiT763bxXNNECx/SQsKjy42LuaV5qQfixgOS4+g6WBu8XJeoPU="

before_install:
  - sudo apt-get install jq dnsutils

script:
  - docker-compose pull
  - docker-compose build
  - (cd websites/audit && docker build -f Dockerfile.cli -t audit-cli .)
  - docker run -e JUST_PRINT_AUDIT_PAGE=1 dappsearth_frontend > audit.html.expected
  - diff audit.html audit.html.expected
  - rm -f audit.html.expected
  - if docker run audit-cli staging.dapps.earth; then echo "This should not have succeeded" && false; else echo "failed as planned"; fi
  - docker run audit-cli dapps.earth

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_AUDIT_PUSH_USER" -p="$DOCKER_AUDIT_PUSH_PASSWORD";
      docker tag audit-cli dappsearth/audit;
      docker push dappsearth/audit;
    fi
  - ./scripts/travis-deploy.sh .env.staging
  - ./scripts/travis-deploy.sh .env
