DOCKER_COMPOSE_VERSION: 1.22.0

env:
  global:
    # Password to decrypt key f1e8c3421e05855e (staging)
    - secure: "dJiBjpvANEau/j36Fp5/XX1L5jBRT9wPE7tHZMO1enqmOFoAVgi2WS1d40ZqAlqJRFmlQBmMHPZDFmOyH7KLPmrCDg7jxN/GcoTN/zxufUnRx6hCYhy3e0uo6MAOSlET+IUzTkP465HnD4+WbwNueHYLYLwjHqSt9Lr3sgf34+nAIoTxw7xPwjgf/TrqKQpwspfAxFNFZkvivSZXioCOucWEhlxmXd38179BVV/xz8HX6D6Bb5rRU8JpjR1cjaWLHPi3bGSjNUTMssDeB2alH/lczzzXHFZb3wmu+jO4ohe//vcJscwvOpe98nA8Zl5STrrIKP7Hs7JcaYC8zJnEDfEeIzXnU/lDPhHO1k6uLrdtqJ9ZycuBFNZ6oCRLSVrXMOQnEjMAkV9STuqLIrSyzWKpUG004txQ4RwbLo7OdRgJZhs2WMTm4knaDg4dEDFCc5pkK6Xk4aRlvOLReN9MiBU4wAVkQXgCfLx/KDYZJcr1fAcplJFB5e5g6QyWuJNosPxDF3/fuOhUxHP06HYCJhm3cbPfxODutQF49PcuHiK9cKGnJdYOCXDX7RunI5pp3/27uFA+ZwnhegiNnRVnaPOLYNKBT84gRWMgX+PQYtTVKzRQ0SG/Q4GV18RaIVG9eHIKqbeR3gRM7HGha1+yFrelQJqcqUkfG07rj9glnhM="
    # Password to decrypt key b62b59370733a386 (prod)
    - secure: "SSfqTVwr0F18ohP+PmYxOup5gOoa3Ebut7+71ZPhY6cRjgR+jmfYX8YLtlB3ZA2fo7TidrmXBu7Eqg+vk23bE5TMThcV563O3pqLbMiyg4kZ12dcKAvV+dAY3a8KUKPk57SRZHCy5Oy/ZACk2g7IoerobTCFi6r1wtS030uT4tUT6iuwIeKZee3k0BY5VhQA6m3TCH/axYQ7eBEHTYq12bBLCUQXzqi524z+/NsCU1b1+gc1Xu2fQp3bR4vIMeqh4WuXSkoxBTNqMhbGgcf+Nl2BEmodeeB1vcMa9Q1ZH7eEuuTePkU2ghGtsctCXadec4eCunUusGTKh2y9JC6qlf5ehfQTof48Zd2KAq+rsyxuQ/lEhxAragZSFmBIRAPqA7j5Xn4WcBRueODypVBkJ2t4SSTrXYmgyx0mE3Jv34DoGBT0kIY681GVIwMjr6rhfLm5zCieVXQ3VQzSBV6Y1fD4MX+Ecomszn/znD91tG6BI16sF8kY4H4HVifN9zpYaCV+9VfTvLRJ+8NQsHPtzLNbC52ZifQqV7rWR48W4nOcN6sopZuPImSOBMoANdn9dlwUytztsPB7Vi/b9jyjAntS9NH9eKtvArYkGosLQRTnFoDmZGjHD9gGbOgPHe3lF2AzEOjGQOa6amDEKOcK4BZ/hOjiUHHlCzthKmjfIEA="

script:
 - docker-compose pull
 - docker-compose build

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ];
    then
      for ENC_KEY in $(cd keys && ls *.enc); do
        chmod 600 "keys/$ENC_KEY";
        KEY=${ENC_KEY%.enc}
        PASSPHRASE_VAR_NAME="TRAVIS_PASSWORD_$KEY";
        echo "Using passphrase from var $PASSPHRASE_VAR_NAME";
        PASSPHRASE="${!PASSPHRASE_VAR_NAME}";
        if [ -z "$PASSPHRASE" ]; then
          echo "$PASSPHRASE_VAR_NAME is unset!";
        else
          echo "Passphrase length is ${#PASSPHRASE}";
          if ssh-keygen -o -p -P "$PASSPHRASE" -N "" -f "keys/$ENC_KEY"; then
            mv "keys/$ENC_KEY" "keys/$KEY.key";
            echo "Unlocked keys/$ENC_KEY into keys/$KEY.key";
          else
            echo "Failed to unlock keys/$ENC_KEY";
          fi;
        fi;
      done;
    fi
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ];
    then
      export ENV=.env.staging;
      (. $ENV && ./scripts/deploy.sh);
    fi
