DOCKER_COMPOSE_VERSION: 1.22.0

env:
  global:
    # Password to decrypt key 1ba30aa02e7c1e07 (staging)
    - secure: "dJiBjpvANEau/j36Fp5/XX1L5jBRT9wPE7tHZMO1enqmOFoAVgi2WS1d40ZqAlqJRFmlQBmMHPZDFmOyH7KLPmrCDg7jxN/GcoTN/zxufUnRx6hCYhy3e0uo6MAOSlET+IUzTkP465HnD4+WbwNueHYLYLwjHqSt9Lr3sgf34+nAIoTxw7xPwjgf/TrqKQpwspfAxFNFZkvivSZXioCOucWEhlxmXd38179BVV/xz8HX6D6Bb5rRU8JpjR1cjaWLHPi3bGSjNUTMssDeB2alH/lczzzXHFZb3wmu+jO4ohe//vcJscwvOpe98nA8Zl5STrrIKP7Hs7JcaYC8zJnEDfEeIzXnU/lDPhHO1k6uLrdtqJ9ZycuBFNZ6oCRLSVrXMOQnEjMAkV9STuqLIrSyzWKpUG004txQ4RwbLo7OdRgJZhs2WMTm4knaDg4dEDFCc5pkK6Xk4aRlvOLReN9MiBU4wAVkQXgCfLx/KDYZJcr1fAcplJFB5e5g6QyWuJNosPxDF3/fuOhUxHP06HYCJhm3cbPfxODutQF49PcuHiK9cKGnJdYOCXDX7RunI5pp3/27uFA+ZwnhegiNnRVnaPOLYNKBT84gRWMgX+PQYtTVKzRQ0SG/Q4GV18RaIVG9eHIKqbeR3gRM7HGha1+yFrelQJqcqUkfG07rj9glnhM="
    # Password to decrypt key b62b59370733a386 (prod)
    - secure: "TrMTZNyXCG3cgqv5jpqQHXCeVbN3SJD71/ZXaSTdQP58gGOt5gAlIHnGPOmNhwKKqQkwIosbkkMcWx2nj5t8WoGH6c8ZNzKQAK+E/ZYZET2V112SX72zqLF5SuKSceX+eT33lolCOyoFVreW6GkURKzDmcTpsnJ0/bUKXJpg3NI3Zfm1dQZ4o8FnjTBKp68vM1AvDCH+dPY9nTUgsS0Gi78uDgZ9Le5GaNKPVo58fa8n+tE2bD0cVFE9o1g8VEIGrsBUmrPjKnX9vlD6A3AWX9obIA6BJ2GHGIroV7sEdLax+AjRAFk+LzRocjRIG9i6+IBnoq2qMirl8yqS7dpql3boZhu362OtmJUC0GAaTVaIYDExMCYjYfs0RoU+Ypwt2sCP/+aWZTf2IjM8pX+2+qQ0HcKBQHQTRVMU0/Of9MAE7TV8Oe6ugiuFZSjQlteauk9d1xw4VpTgYVS4ng0zZs6s8TjsZ9tXvPWpyhY7Vpa0qSNCg7sNjXVdBTEMjZHnsZv67c43eZmmr2n8aSaqhUmRzpVaswkZe+qozAWo9LMxYSbIHf3klKBRGzd4YhRbkCcGdEI8dDmUI5xM9PRcHzARzpYzx7dnywwtP30dSPBtYlqrvA68kiQ+4eSitD3JUXyD0wcDfGAV4Tk0DDUwJ7wOhBwR+agGclA+pHAFWHM="

before_install:
  - sudo apt-get jq

script:
 - docker-compose pull
 - docker-compose build

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ];
    then
      for ENC_KEY in $(cd keys && ls *.enc); do
        chmod 600 "keys/$ENC_KEY";
        KEY=${ENC_KEY%.enc}
        PASSPHRASE_VAR_NAME="TRAVIS_PASSWORD_$KEY";
        echo "Using passphrase from var $PASSPHRASE_VAR_NAME";
        PASSPHRASE="${!PASSPHRASE_VAR_NAME}";
        if [ -z "$PASSPHRASE" ]; then
          echo "$PASSPHRASE_VAR_NAME is unset!";
        else
          echo "Passphrase length is ${#PASSPHRASE}";
          if ssh-keygen -o -p -P "$PASSPHRASE" -N "" -f "keys/$ENC_KEY"; then
            mv "keys/$ENC_KEY" "keys/$KEY.key";
            echo "Unlocked keys/$ENC_KEY into keys/$KEY.key";
          else
            echo "Failed to unlock keys/$ENC_KEY";
          fi;
        fi;
      done;
    fi
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ];
    then
      export ENV=.env.staging;
      (. $ENV && ./scripts/deploy.sh);
    fi
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ];
    then
      export ENV=.env;
      (. $ENV && ./scripts/deploy.sh);
    fi
