DOCKER_COMPOSE_VERSION: 1.22.0

env:
  global:
    # TRAVIS_PASSWORD_a4a4667750982126 (to deploy .env.staging)
    - secure: "WEaefnY6RE/8e9veCkc5bH8taEAnbOebrq3LFLy8Won+cQGdFP8YZE+kRw+iAZstL4PpMSZ6We0czXF0FybSgRrwFdr/oHGnx/s4r0J4i+aTUK5Tl5J9W78gJQpuCxA0ZQ/nHn8tPRG947lAvRGjlbl8i/QnsYmGt3k4dPrTwtzMjfM0IldCGiRS7a4pptobz/9R7SG3n/DEdcO+J6q665/PiYWOAnTG1DzUA0V+HtXlr8qwyHETrfcMOi075/LEXHydiH6OB+kL7LbA8JQ7hqLLpXJDaMyh0+99W+eIndIoK2cpZov8BMKFzeSiFf/b77nLpHl/3DzeHfTXQQFHHPcfPR6dClVQHriQQX9vdDLkGciiEHpPN8SWXWJVTX8baxJ1NsnleVk/dUF9i0KlJlaFkXexmJDNHQmK2XOHw+cvwqtw6f7FI2x/kZTNFWjfL//IMllcgNu3bmUQMyOtUaoVHwRVbEj43F6esh0oSPzWbnMD02bUJHkstdmt6IC++2oDDCTXm5tI+wu37ASEUCqD73ewFn05Zs0txlsCg1XzhFSPM7Gya/BMx5B0TlQO84xdCbJc0AyLoE/fVTvpO4sOkHvNvZzzTXQhztAeCk2TIX4A7o/Y6GugXGg62xuBOqKUOcKAJV+Yaf5MEPbfA81RsKsY7bRz1R/Axi72NNg="
    # Password to decrypt key b62b59370733a386 (prod)
    - secure: "TrMTZNyXCG3cgqv5jpqQHXCeVbN3SJD71/ZXaSTdQP58gGOt5gAlIHnGPOmNhwKKqQkwIosbkkMcWx2nj5t8WoGH6c8ZNzKQAK+E/ZYZET2V112SX72zqLF5SuKSceX+eT33lolCOyoFVreW6GkURKzDmcTpsnJ0/bUKXJpg3NI3Zfm1dQZ4o8FnjTBKp68vM1AvDCH+dPY9nTUgsS0Gi78uDgZ9Le5GaNKPVo58fa8n+tE2bD0cVFE9o1g8VEIGrsBUmrPjKnX9vlD6A3AWX9obIA6BJ2GHGIroV7sEdLax+AjRAFk+LzRocjRIG9i6+IBnoq2qMirl8yqS7dpql3boZhu362OtmJUC0GAaTVaIYDExMCYjYfs0RoU+Ypwt2sCP/+aWZTf2IjM8pX+2+qQ0HcKBQHQTRVMU0/Of9MAE7TV8Oe6ugiuFZSjQlteauk9d1xw4VpTgYVS4ng0zZs6s8TjsZ9tXvPWpyhY7Vpa0qSNCg7sNjXVdBTEMjZHnsZv67c43eZmmr2n8aSaqhUmRzpVaswkZe+qozAWo9LMxYSbIHf3klKBRGzd4YhRbkCcGdEI8dDmUI5xM9PRcHzARzpYzx7dnywwtP30dSPBtYlqrvA68kiQ+4eSitD3JUXyD0wcDfGAV4Tk0DDUwJ7wOhBwR+agGclA+pHAFWHM="

before_install:
  - sudo apt-get install jq

script:
 - docker-compose pull
 - docker-compose build

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ];
    then
      export ENV=.env.staging;
      (. $ENV && ./scripts/deploy.sh);
    fi
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ];
    then
      export ENV=.env;
      (. $ENV && ./scripts/deploy.sh);
    fi
