DOCKER_COMPOSE_VERSION: 1.22.0

env:
  global:
    # TRAVIS_PASSWORD_73b685a11552adf5 (to deploy .env.staging)
    - secure: "kZSYAtR9wohAyb/mgZm0GJhFxn2+W2YhoJa7atY7jjB+9YX3L33HxpAoWgSphgqrqvZ32ztME+BF9dvrBGTbGCtNhp9E2CiuGuGlkIUfw8l1jagyUd9NkoDN9DOsP4XDw4gI2gmw53Sc65HcbauuytVCjd9PMeQ2AjJjIZ9YXGoyudtr2XTzyAKXjQlzEFvgrCciXreFIv1uGIWTLBsV21XV7/E7ejWIROX0jLOXSCkTkvXkAn/SA6LTVYXtHvcE066utJdb3wSjkABqqV9YMkT5YZuZAq+OCh0fZX7CcSKvOqUoHKKHpEjhhH1oQ8P+fC8bUMunWo8CbNQJuwYvm2wdieva+3aLovAEYNXOTC8DO3DGFk2mChzdUgU5WZaxozszUutBxwU7jbijd2brCt8VdhacpiDJ5bvscEOE5ffJyy/ku1F4sqgUVkwrzvZRuLzBref1gWwSy6VhBiZJ8k5qg56P/wLG7CZG3gDUqWo7kruu7caw/TnPJaGItvIDLGvLIJAajVhaog7fjVP4IBQhjoeV4kHuNxWjEPXMUEShnKACEb3qtpuLDy77Pn+nbh0ytWdUo374SsUFupNIj+cuMDSTM2sCIEirDj7lEH9WyAJYyYiDl+wV/gBYYdJQA+sKJu89KRlEMUshG3p2Of7GWkoHvKIICQgfWoz9IrA="
    # TRAVIS_PASSWORD_28836b2dd695e49e (to deploy .env)
    - secure: "fyfYvZQ66Y+JQh9DOOSznJWgulYemEhkULAEMRkNR6m1MAtxtqwgXE5z90Bg1RbIlzZlZ/c3gHFeCVP0pSHT0NlxR5tyaJxN3gLxfVe9jerG44DMvKAxHn0dK1dsfvru3OU6ac01dCmnntGOIKjAncA0kOLnhRWrd1YPWPyYLdHsQneYjU+SkhhwNHqGEUCjojx0hw4hAuWKuQ2zJ2Nzt4kWg+cfdCaI9cTcnk2Hh2UHyQ3a8MNwfPrmjpLBUPxZPeFOLHR3gTcgAcjMayvQrS71kdz6G/7LTInyc9y6VhdJQaxreNWK74V+ORR61xj2+BFwsF6u7+u7L8X+WUy69Ec4AQX/kBCotfbNjROKFVOCZlK2AunLzGy7aQoESwSJjYJ2t1ArAJyRf+T4sXJ7k1mFthGp/XO1a0B1a1t4+mq6VQpKC73vDNRCoHNDgaIrPE2CFtsv6awD0YHd3MhounXUt5VtoYOOXn4MUZZIZrV9EzkW0pJnzTAXGACSFnPPv7ZIf647W2qyuYb1ymd6xKQnzUnzVHnD3RJVxBlqYeDTAQTJtfr8u17p1N6KaNz1GAB9bxjO4tmXVakQRjkNp028Yhs9r+N+cjgVCtp7OpwVQfajILa2CXOQtqMcrtlpAZvqpcn9lsgcYA59aj8xFFWFeZnWBoEOjtyArVNvhOY="

before_install:
  - sudo apt-get install jq

script:
 - docker-compose pull
 - docker-compose build

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ];
    then
      export ENV=.env.staging;
      (. $ENV && ./scripts/deploy.sh);
    fi
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ];
    then
      export ENV=.env;
      (. $ENV && ./scripts/deploy.sh);
    fi
