version: '3'

# Need to provide the following environment variables when running:
# - BASE_DOMAIN (accessible to target audience, not necessarily public internet)
# - NS_DOMAIN (accessible to public internet)

services:
  proxy:
    restart: always
    build: proxy
    container_name: proxy
    environment:
      - BASE_DOMAIN
      - HAS_SSL=1
    depends_on:
      - ipfs
      - swarm
  frontend:
    restart: always
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: frontend
    environment:
      - BASE_DOMAIN
    volumes:
      - certs:/etc/nginx/certs:ro
      - /var/log/dapps.earth-integrity:/var/log/dapps.earth-integrity:ro
    ports:
      - "80:8080"
      - "443:443"
    depends_on:
      - proxy
      - ssl-renewer
      - geth
      - swarm
  ssl-renewer:
    restart: always
    build: ssl-renewer
    container_name: ssl-renewer
    environment:
      - BASE_DOMAIN
      - NS_DOMAIN
      - HOSTS=$BASE_DOMAIN *.$BASE_DOMAIN *.ipfs.$BASE_DOMAIN *.swarm.$BASE_DOMAIN *.eth.swarm.$BASE_DOMAIN *.test.swarm.$BASE_DOMAIN
      - MAX_SSL_CERTIFICATE_AGE_DAYS=14
    volumes:
      - ssl-renewer-successes:/successes
      - certs:/etc/nginx/certs
    ports:
      - "53:53/udp"
  ipfs:
    restart: always
    build: ipfs
    container_name: ipfs
    ports:
      - "4001:4001"
    volumes:
      - ipfs-data:/data/ipfs
  geth:
    restart: always
    build: geth
    container_name: geth
    ports:
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - geth-data:/home/gethuser/.ethereum
  swarm:
    restart: always
    build: swarm
    container_name: swarm
    depends_on:
      - geth
    volumes:
      - swarm-data:/home/swarmuser/data
    # TODO: ports?

volumes:
  ssl-renewer-successes:
  certs:
  ipfs-data:
  geth-data:
  swarm-data:
