version: '3'

# Need to provide the following environment variables when running:
# - BASE_DOMAIN (accessible to target audience, not necessarily public internet)
# - NS_DOMAIN (accessible to public internet)
# - ADMIN_EMAIL

services:
  proxy:
    restart: always
    build: proxy
    environment:
      - BASE_DOMAIN
      - HAS_SSL=1
    depends_on:
      - ipfs
  frontend:
    restart: always
    build:
      context: .
      dockerfile: nginx/Dockerfile
    environment:
      - BASE_DOMAIN
    volumes:
      - certs:/etc/nginx/certs:ro
      - /var/log/dapps.earth-integrity:/var/log/dapps.earth-integrity:ro
    ports:
      - "80:8080"
      - "443:443"
    depends_on:
      - proxy
      - ssl-renewer
  ssl-renewer:
    restart: always
    build: ssl-renewer
    environment:
      - ADMIN_EMAIL
      - BASE_DOMAIN
      - NS_DOMAIN
      - HOSTS=$BASE_DOMAIN *.$BASE_DOMAIN *.ipfs.$BASE_DOMAIN *.eth.swarm.$BASE_DOMAIN
      - MAX_SSL_CERTIFICATE_AGE_DAYS=7
    volumes:
      - ssl-renewer-auth:/acme-dns-auth
      - ssl-renewer-successes:/successes
      - certs:/etc/nginx/certs
    depends_on:
      - acme-dns
  acme-dns:
    restart: always
    build: acme-dns
    environment:
      - BASE_DOMAIN
      - NS_DOMAIN
      - ADMIN_EMAIL
    ports:
      - "53:53/udp"
    volumes:
      - acme-dns-data:/var/lib/acme-dns
  ipfs:
    restart: always
    build: ipfs
    ports:
      - "4001:4001"
    volumes:
      - ipfs-data:/data/ipfs

volumes:
  acme-dns-data:
  ssl-renewer-auth:
  ssl-renewer-successes:
  certs:
  ipfs-data:
